# GENERATED BY ChatGPT

import os
import subprocess
from PIL import Image

def is_image_compressed(file_path):
    """
    Checks if an image file is compressed by examining its alpha channel using the Pillow library.
    Returns True if the image is compressed, False otherwise.
    """
    try:
        with Image.open(file_path) as img:
            return img.mode != "RGBA"
    except (IOError, OSError):
        return False

def get_uncompressed_images(folder_path):
    """
    Returns a list of image files in the given folder that are uncompressed.
    """
    uncompressed_images = []
    for file_name in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file_name)
        if os.path.isfile(file_path) and file_name.lower().endswith('.png'):
            if not is_image_compressed(file_path):
                uncompressed_images.append(file_name)
    return uncompressed_images

def compress_image(file_path):
    """
    Compresses the given image file using the pngquant command.
    """
    command = ['pngquant', file_path]
    subprocess.run(command, capture_output=True)

# Prompt the user for the folder path
folder_path = input("Enter the path of the folder containing PNG images: ")

# Get the list of uncompressed image files
uncompressed_images = get_uncompressed_images(folder_path)

# Output the uncompressed image file names
print("Uncompressed Image Files:")
for image_file in uncompressed_images:
    print(image_file)

# Compress the uncompressed images
print("Compressing Images...")
for image_file in uncompressed_images:
    image_path = os.path.join(folder_path, image_file)
    compress_image(image_path)

print("Compression complete!")
